INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'AL', N'Alabama', 1)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'AK', N'Alaska', 2)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'AZ', N'Arizona', 3)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'AR', N'Arkansas', 4)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'CA', N'California', 5)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'CO', N'Colorado', 6)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'CT', N'Connecticut', 7)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'DE', N'Delaware', 8)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'DC', N'District Of Columbia', 9)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'FL', N'Florida', 10)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'GA', N'Georgia', 11)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'HI', N'Hawaii', 12)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'ID', N'Idaho', 13)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'IL', N'Illinois', 14)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'IN', N'Indiana', 15)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'IA', N'Iowa', 16)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'KS', N'Kansas', 17)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'KY', N'Kentucky', 18)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'LA', N'Louisiana', 19)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'ME', N'Maine', 20)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'MD', N'Maryland', 21)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'MA', N'Massachusetts', 22)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'MI', N'Michigan', 23)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'MN', N'Minnesota', 24)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'MS', N'Mississippi', 25)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'MO', N'Missouri', 26)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'MT', N'Montana', 27)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'NE', N'Nebraska', 28)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'NV', N'Nevada', 29)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'NH', N'New Hampshire', 30)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'NJ', N'New Jersey', 31)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'NM', N'New Mexico', 32)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'NY', N'New York', 33)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'NC', N'North Carolina', 34)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'ND', N'North Dakota', 35)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'OH', N'Ohio', 36)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'OK', N'Oklahoma', 37)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'OR', N'Oregon', 38)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'PA', N'Pennsylvania', 39)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'RI', N'Rhode Island', 40)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'SC', N'South Carolina', 41)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'SD', N'South Dakota', 42)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'TN', N'Tennessee', 43)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'TX', N'Texas', 44)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'UT', N'Utah', 45)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'VT', N'Vermont', 46)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'VA', N'Virginia', 47)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'WA', N'Washington', 48)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'WV', N'West Virginia', 49)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'WI', N'Wisconsin', 50)
INSERT [dbo].[States] ([StateCode], [StateName], [DisplayOrder]) VALUES (N'WY', N'Wyoming', 51)