//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TANWeb.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TANResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TANResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TANWeb.Resources.TANResource", typeof(TANResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/Shared/Templates/_2FALoginOTPEmailTemplete.cshtml.
        /// </summary>
        internal static string _2FAOTPEmailTemplatePath {
            get {
                return ResourceManager.GetString("2FAOTPEmailTemplatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdminUser:ConfirmedEmail.
        /// </summary>
        internal static string AdminConfirmedEmail {
            get {
                return ResourceManager.GetString("AdminConfirmedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdminUser:Email.
        /// </summary>
        internal static string AdminEmail {
            get {
                return ResourceManager.GetString("AdminEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin:FirstName.
        /// </summary>
        internal static string AdminFirstName {
            get {
                return ResourceManager.GetString("AdminFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin:LastName.
        /// </summary>
        internal static string AdminLastName {
            get {
                return ResourceManager.GetString("AdminLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdminUser:Password.
        /// </summary>
        internal static string AdminPassword {
            get {
                return ResourceManager.GetString("AdminPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdminUser:PhoneNumberConfirmed.
        /// </summary>
        internal static string AdminPhoneNumberConfirmed {
            get {
                return ResourceManager.GetString("AdminPhoneNumberConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdminUser:TwoFactorEnabled.
        /// </summary>
        internal static string AdminTwoFactorEnabled {
            get {
                return ResourceManager.GetString("AdminTwoFactorEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdminUser:UserName.
        /// </summary>
        internal static string AdminUserName {
            get {
                return ResourceManager.GetString("AdminUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications:PBJSnap.
        /// </summary>
        internal static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/Shared/Templates/_ConfirmAccountEmailTemplate.cshtml.
        /// </summary>
        internal static string ConfirmAccountEmailTemplatePath {
            get {
                return ResourceManager.GetString("ConfirmAccountEmailTemplatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupportedCulture:DefaultRequestCulture.
        /// </summary>
        internal static string DefaultRequestCulture {
            get {
                return ResourceManager.GetString("DefaultRequestCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultUser:ConfirmedEmail.
        /// </summary>
        internal static string DefaultUserConfirmedEmail {
            get {
                return ResourceManager.GetString("DefaultUserConfirmedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultUser:Email.
        /// </summary>
        internal static string DefaultUserEmail {
            get {
                return ResourceManager.GetString("DefaultUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultUser:FirstName.
        /// </summary>
        internal static string DefaultUserFirstName {
            get {
                return ResourceManager.GetString("DefaultUserFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultUser:LastName.
        /// </summary>
        internal static string DefaultUserLastName {
            get {
                return ResourceManager.GetString("DefaultUserLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultUser:Password.
        /// </summary>
        internal static string DefaultUserPassword {
            get {
                return ResourceManager.GetString("DefaultUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultUser:PhoneNumberConfirmed.
        /// </summary>
        internal static string DefaultUserPhoneNumberConfirmed {
            get {
                return ResourceManager.GetString("DefaultUserPhoneNumberConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultUser:TwoFactorEnabled.
        /// </summary>
        internal static string DefaultUserTwoFactorEnabled {
            get {
                return ResourceManager.GetString("DefaultUserTwoFactorEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultUser:UserName.
        /// </summary>
        internal static string DefaultUserUserName {
            get {
                return ResourceManager.GetString("DefaultUserUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been deleted successfully.
        /// </summary>
        internal static string DeleteMsg {
            get {
                return ResourceManager.GetString("DeleteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application:EntityManager.
        /// </summary>
        internal static string EntityManager {
            get {
                return ResourceManager.GetString("EntityManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong ! Try again later..
        /// </summary>
        internal static string ErrorMsg {
            get {
                return ResourceManager.GetString("ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/Shared/Templates/_ResetPasswordEmailTemplate.cshtml.
        /// </summary>
        internal static string ForgotPasswordEmailTemplatePath {
            get {
                return ResourceManager.GetString("ForgotPasswordEmailTemplatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps:Inventory.
        /// </summary>
        internal static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Inventory/Home/Index.
        /// </summary>
        internal static string InventoryDashboardPath {
            get {
                return ResourceManager.GetString("InventoryDashboardPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /pbjsnap/dashboard.
        /// </summary>
        internal static string PBJDashboardPath {
            get {
                return ResourceManager.GetString("PBJDashboardPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps:PBJSnap.
        /// </summary>
        internal static string PBJSnap {
            get {
                return ResourceManager.GetString("PBJSnap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /TelecomReporting/Home/Index.
        /// </summary>
        internal static string ReportingDashboardPath {
            get {
                return ResourceManager.GetString("ReportingDashboardPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/Shared/Templates/_SendResetPasswordEmailTemplate.cshtml.
        /// </summary>
        internal static string ResetPasswordEmailTemplatePath {
            get {
                return ResourceManager.GetString("ResetPasswordEmailTemplatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Saved !.
        /// </summary>
        internal static string SuccessMsg {
            get {
                return ResourceManager.GetString("SuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuperAdmin:ConfirmedEmail.
        /// </summary>
        internal static string SuperAdminConfirmedEmail {
            get {
                return ResourceManager.GetString("SuperAdminConfirmedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuperAdmin:Email.
        /// </summary>
        internal static string SuperAdminEmail {
            get {
                return ResourceManager.GetString("SuperAdminEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuperAdmin:FirstName.
        /// </summary>
        internal static string SuperAdminFirstName {
            get {
                return ResourceManager.GetString("SuperAdminFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuperAdmin:LastName.
        /// </summary>
        internal static string SuperAdminLastName {
            get {
                return ResourceManager.GetString("SuperAdminLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuperAdmin:Password.
        /// </summary>
        internal static string SuperAdminPassword {
            get {
                return ResourceManager.GetString("SuperAdminPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuperAdmin:PhoneNumberConfirmed.
        /// </summary>
        internal static string SuperAdminPhoneNumberConfirmed {
            get {
                return ResourceManager.GetString("SuperAdminPhoneNumberConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuperAdmin:TwoFactorEnabled.
        /// </summary>
        internal static string SuperAdminTwoFactorEnabled {
            get {
                return ResourceManager.GetString("SuperAdminTwoFactorEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuperAdmin:UserName.
        /// </summary>
        internal static string SuperAdminUserName {
            get {
                return ResourceManager.GetString("SuperAdminUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps:Reporting.
        /// </summary>
        internal static string TelecomReporting {
            get {
                return ResourceManager.GetString("TelecomReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been updated successfully.
        /// </summary>
        internal static string UpdateMsg {
            get {
                return ResourceManager.GetString("UpdateMsg", resourceCulture);
            }
        }
    }
}
